version: '3'
services:
        jenkins:
            container_name: jenkins
            image: jenkins/jenkins:lts
            ports:
                    - "5050:8080"
            volumes:
                    - "$PWD/jenkins_home:/opt/jenkins_home"
            networks:
                    - net
networks:
  net:
